#!/usr/bin/env node

"use strict";

require("./lib/utils");
const optimist = require("optimist");
const argv = optimist
    .usage("$0 [-h][-m][-s] <input>".yellow)
    .option("h", {
      alias: "help",
      description: "Show usage"
    })
    .option("m", {
      alias: "meta",
      description: "Update meta data"
    })
    .option("s", {
      alias: "server",
      description: "Start server"
    })
    .option("t", {
      alias: "thumbnail",
      description: "Create thumbnails"
    })
    .boolean(["h", "m", "s", "t"])
    .check((argv) => {
      if (argv.help)
        throw "";
      
      if (argv._.length === 0)
        throw "No input directory specified";
    })
    .argv;

const MetaDataSync = require("./lib/sync").MetaDataSync;
const server = require("./lib/server");

const inputDir = argv._[0];
let metaSync = new MetaDataSync(inputDir);
let filenames = metaSync.sync({meta: argv.meta, thumbnail: argv.thumbnail});
if (argv.server) {
  filenames = filenames.then(() => server.createServer(inputDir, metaSync));
}
filenames.catch((err) => console.error(`Bootstrap error: ${err.stack}`));
